from tkinter import*
from tkinter import messagebox
def apply():
    import csv
    with open('addApp.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["ID card", "Name", "address","phone number","university degree","experience","skills"])
        writer.writerow([E1.get(),E2.get(),E3.get(),E4.get(),E5.get(),E6.get(),E7.get()])
        msg = messagebox.showinfo("add application","your application has been added")
def addApply():
    main = Tk()
    main.title("apply")
    L1= Label(main, text="ID card").grid(row=0, column=0)
    E1 = Entry(main, bd=5)
    E1.grid(row=0, column=1)
    L2= Label(main, text="name").grid(row=1, column=0)
    E2 = Entry(main, bd=5)
    E2.grid(row=1, column=1)
    L3= Label(main, text="address").grid(row=2, column=0)
    E3 = Entry(main, bd=5)
    E3.grid(row=2, column=1)
    L4= Label(main, text="phone number").grid(row=3, column=0)
    E4 = Entry(main, bd=5)
    E4.grid(row=3, column=1)
    L5= Label(main, text="university degree").grid(row=4, column=0)
    E5 = Entry(main, bd=5)
    E5.grid(row=4, column=1)
    L6= Label(main, text="professional experience").grid(row=5, column=0)
    E6 = Entry(main, bd=5)
    E6.grid(row=5, column=1)
    L7= Label(main, text="skills").grid(row=6, column=0)
    E7 = Entry(main, bd=5)
    E7.grid(row=6,column=1)
    B2= Button(main, text=" Apply ", command=apply).grid(row=7, column=1)
    main.mainloop()
